#!/usr/bin/env bash
# Redirection:

# Install nginx web server:
sudo apt -y update
sudo apt -y upgrade
sudo apt -y install nginx
sudo chown -R ubuntu /var/www/
touch /var/www/html/index.html
echo "Hello World!" > /var/www/html/index.html

# Add the location block for redirection
sudo sed -i '/^}$/i \ \ \ \ location /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
sudo service nginx restart
