#!/usr/bin/env bash
sudo apt-get -y update
sudo apt-get -y install nginx
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
sudo sed -i '/^}$/i \ \n\tlocation \/redirect_me {return 301 https://www.youtube.com/watch?v=TUiGnN6F0l4&list=PL1fXq6XDoU515Lj8GehT3Dck2uQAe0iAN;}' /etc/nginx/sites-available/default
sudo sed -i '/^}$/i \ \n\tlocation @404 {return 404 "Ceci n'\''est pas une page\\n";}' /etc/nginx/sites-available/default
sudo sed -i 's/=404/@404/g' /etc/nginx/sites-available/default
sed -i "s/include \/etc\/nginx\/sites-enabled\/\*;/include \/etc\/nginx\/sites-enabled\/\*;\n\tadd_header X-Served-By \"$HOSTNAME\";/" /etc/nginx/nginx.conf
service nginx restart
