#!/usr/bin/env bash
#HAproxyyiy
apt-get update
apt-get install haproxy -y

echo "
frontend eyes
    bind *:80
    default_backend heart

backend heart
    balance roundrobin
    server 387178-web-01 54.173.240.169:80 check
    server 387178-web-02 52.201.159.101:80 check
" >> /etc/haproxy/haproxy.cfg
service haproxy restart
