#!/bin/bash

# Utilise la commande 'ps' pour afficher les informations des processus
# Les options -e permettent d'afficher tous les processus, même ceux sans TTY
# Les options -o spécifient les colonnes que nous voulons afficher
ps -e -o user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,command | head -n 50
